### ISSUE TITLE
X-Real-Ip and X-Forwarded-For can be spoofed

### ISSUE THREAD

**Issue by VoidingWarranties** [johnathanhowell/reqlimit#2]
Hi friend,

PR #1 introduced support for X-Real-Ip and X-Forwarded-For. Both can be trivially spoofed, making this library not ideal for rate limiting adversaries. Maybe this intention of this library isn't adversarial situations, but I couldn't think of a non-adversarial reason to rate limit so I thought I'd bring it up.

Whadya think?

**Comment by avahowell** [comment]
The intention is definitely for limiting adversaries, x-real-ip and x-forwarded-for should probably be ignored.
